# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [github-action]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        env:
          REACT_APP_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.REACT_APP_CONTENTFUL_ACCESS_TOKEN }}
          REACT_APP_CONTENTFUL_PREVIEW_API: ${{ secrets.REACT_APP_CONTENTFUL_PREVIEW_API }}
          REACT_APP_CONTENTFUL_SPACE_ID: ${{ secrets.REACT_APP_CONTENTFUL_SPACE_ID }}
          REPO_SECRET: ${{ secrets.REPO_SECRET }}
          CHAMP: champ
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: ls -la
      - run: pwd
      - run: echo $REACT_APP_CONTENTFUL_ACCESS_TOKEN
      - run: echo $CHAMP
      - run: echo $GITHUB_REPOSITORY
      - run: echo $REPO_SECRET
      - run: export CHAMP=$CHAMP
      - run: export REPO_SECRET=$REPO_SECRET
      - run: npm i
      - run: printenv
      # - run: npm run build --if-present
      # - run: npm test
