# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [github-action]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      # REACT_APP_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.REACT_APP_CONTENTFUL_ACCESS_TOKEN }}
      REACT_APP_CONTENTFUL_PREVIEW_API: ${{ secrets.REACT_APP_CONTENTFUL_PREVIEW_API }}
      REACT_APP_CONTENTFUL_SPACE_ID: ${{ secrets.REACT_APP_CONTENTFUL_SPACE_ID }}
      REPO_SECRET: ${{ secrets.REPO_SECRET }}
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
        env:
          REACT_APP_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.REACT_APP_CONTENTFUL_ACCESS_TOKEN }}
      - name: Create .env
        run: |
          touch .env
          echo REACT_APP_CONTENTFUL_ACCESS_TOKEN=${{ secrets.REACT_APP_CONTENTFUL_ACCESS_TOKEN }} >> .env
          echo REPO_SECRET=${{ secrets.REPO_SECRET }} >> .env
          ls -la
          cat .env
      # - run: echo ${{ env.CHAMP }}
      # run: npm -v
      # run: echo $GITHUB_REPOSITORY
      # run: echo $REPO_SECRET >> test.md
      # run: ls
      # run: cat test.md
      # run: npm ci
      # run: printenv
      # - run: npm run build --if-present
      # - run: npm test
