name: Nextjs CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Create .env
        run: |
          touch .env
          echo REACT_APP_CONTENTFUL_ACCESS_TOKEN=${{ secrets.REACT_APP_CONTENTFUL_ACCESS_TOKEN }} >> .env
          echo REACT_APP_CONTENTFUL_PREVIEW_API=${{ secrets.REACT_APP_CONTENTFUL_PREVIEW_API }} >> .env
          echo REACT_APP_CONTENTFUL_SPACE_ID=${{ secrets.REACT_APP_CONTENTFUL_SPACE_ID }} >> .env
          cat .env
      - name: Install and Build 🔧
        run: |
          npm ci
          npm run clean
          npm run build
          npm run export
          echo nextjs.twinsynergy.co.th >> out/CNAME
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
