name: Nextjs CI

on:
  push:
    branches: [github-action]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Create .env
        run: |
          touch .env
          echo REACT_APP_CONTENTFUL_ACCESS_TOKEN=${{ secrets.REACT_APP_CONTENTFUL_ACCESS_TOKEN }} >> .env
          echo REACT_APP_CONTENTFUL_PREVIEW_API=${{ secrets.REACT_APP_CONTENTFUL_PREVIEW_API }} >> .env
          echo REACT_APP_CONTENTFUL_SPACE_ID=${{ secrets.REACT_APP_CONTENTFUL_SPACE_ID }} >> .env
          cat .env
      - run: npm ci
      - run: npm run build
      - run: npm run export
      - run: echo nextjs.twinsynergy.co.th >> out/CNAME
      - run: npm run deploy
